name: Update README

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *" # Se ejecuta cada hora

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Update README content
        run: |
          echo "🕒 Last updated: $(date)" > README.md

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add README.md
          git commit -m "Updated README automatically"
          git push
